# Generated by Django 5.0 on 2023-12-31 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classmonitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
