# Generated by Django 5.0 on 2023-12-31 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classmonitor', '0003_alter_classrooms_teacher_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classrooms',
            name='teacher_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_teacher', to='classmonitor.teachers'),
        ),
    ]
